### ISSUE TITLE
Burrito should not ping ping for "clear" spelled out

### ISSUE THREAD

**Issue by BoxFromXbox** [Burrito-Devs/burrito#8]
![image](https://github.com/Burrito-Devs/burrito/assets/145508525/3cc5d4a3-1bc6-4486-b292-bf45da04b4e5)

**Comment by the-bernie** [comment]
This isn't a simple issue. Because messages like the one you posted do not follow proper convention, trying to handle such cases will always result in false negatives. And for a tool like Burrito, false negatives are far worse than false positives. Burrito does what is reasonably possible to prevent false positives, but to remove them completely is impossible without introducing even more false negatives.

Example:

1. A character named "Clear Skies" is in 1DQ1-A
2. In accordance with proper intel reporting guidelines, somebody drags the system name and character name into char
3. The messages that appears in the logs is "1DQ1-A Clear Skies"
4. This message contains the word "clear" and thus does not produce RangeOfSystem or RangeOfCharacter events, so no alerts occur

Chatlogs only show the info that is displayed in the in-game chat windows, so it is impossible to detect/group words that correspond to in-game links. It would be extremely expensive to try and figure out whether or not the word "clear" is part of a character name in the cited case. Additionally, if the cited post was well-formatted, Burrito would have been able to detect that this message should not have produced RangeOfSystem events.

Because this is a problem that I have deliberated on for a very long time prior to this reporting, I am going to close this issue. But, if you present a well-researched solution that you believe can fix this, then please open a PR with tests so I can review it.
